version: "3"
services:
    frontend:
        build:
            context: ./react_client
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
    backend:
        build:
            context: ./flask_server
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
