version: "3"
services:
    frontend:
        build:
            context: ./react_client
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        # command: ["yarn", "start"]
    backend:
        build:
            context: ./flask_server
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        # command: ["gunicorn", "--bind", "0.0.0.0:5000", "wsgi:app"]
