export const gameStages: { [key: number]: string } = {
  0: "Pre-bosses",
  1: "Pre-Hardmode",
  2: "Pre-mech bosses",
  3: "Pre-Plantera",
  4: "Pre-Golem",
  5: "Pre-Lunar Events",
  6: "Endgame",
};

export const roleClasses = {
  melee: {
    border: "border-melee",
    bg: "bg-melee",
    hoverBg: "hover:bg-melee",
    accent: "accent-melee",
    text: "text-melee",
    decoration: "decoration-melee",
  },
  ranged: {
    border: "border-ranged",
    bg: "bg-ranged",
    hoverBg: "hover:bg-ranged",
    accent: "accent-ranged",
    text: "text-ranged",
    decoration: "decoration-ranged",
  },
  magic: {
    border: "border-magic",
    bg: "bg-magic",
    hoverBg: "hover:bg-magic",
    accent: "accent-magic",
    text: "text-magic",
    decoration: "decoration-magic",
  },
  summoner: {
    border: "border-summoner",
    bg: "bg-summoner",
    hoverBg: "hover:bg-summoner",
    accent: "accent-summoner",
    text: "text-summoner",
    decoration: "decoration-summoner",
  },
  mixed: {
    border: "border-mixed",
    bg: "bg-mixed",
    hoverBg: "hover:bg-mixed",
    accent: "accent-mixed",
    text: "text-mixed",
    decoration: "decoration-mixed",
  },
  tank: {
    border: "border-tank",
    bg: "bg-tank",
    hoverBg: "hover:bg-tank",
    accent: "accent-tank",
    text: "text-tank",
    decoration: "decoration-tank",
  },
  healer: {
    border: "border-healer",
    bg: "bg-healer",
    hoverBg: "hover:bg-healer",
    accent: "accent-healer",
    text: "text-healer",
    decoration: "decoration-healer",
  },
};
