#!/bin/bash

set -e

cd "$(dirname "$0")/.."

export PATH=".venv/bin:$PATH"

python flask-server/game-wiki-scraper.py

if [ -f all-items.json ]; then
    mv all-items.json data/
fi
if [ -f game-stages.json ]; then
    mv game-stages.json data/
fi
