name: "CI: Test Backend"
on:
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Python Setup
              uses: actions/setup-python@v4.2.0
            - name: BE linting
              run: |
                  python -m pip install black isort
                  python -m black flask_server/*.py --check
                  python -m isort --check --diff flask_server/*.py
