name: "CI: Test Backend"
on:
    pull_request:
        paths:
            - "flask_server/**"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Python Setup
              uses: actions/setup-python@v4.2.0
            - name: BE linting
              run: |
                  python -m pip install black isort
                  python -m black flask_server/src --check
                  python -m isort --check --diff flask_server/src
