name: CI
on:
  pull_request:
    types: [opened, reopened]

env:
  IN_TEST: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - uses: dcodeIO/setup-node-nvm@v4
      - name: build
        run: ./build
        # npm run build, also sort the ts folder
      - name: runtests
        run: ./runtests
